version: '3.5'
services:
  postgres:
    container_name: parking-control-db
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: